### ISSUE TITLE
Loading the entire database NOT in memory for scalability

### ISSUE THREAD

**Issue by Yazington** [gusye1234/nano-vectordb#5]
If this is being created for multiple users (maybe one day millions), we need to scale. Having in memory with numpy is simple, but if I was to query something, it would load the entire database in memory

Suggestions:
1. sharding
2. lazy loading
3. caching

**Comment by gusye1234** [comment]
Yeah! In fact I'm planning to improve this Project with multi-user support

**Comment by gusye1234** [comment]
@Yazington Hi, I added a naive beta support for multi-tenancy, maybe you can do a proof-reading of this feature❤️
