### ISSUE TITLE
Is there a way to unhash the content or do you have a switch to turn off hashing before ingest?

### ISSUE THREAD

**Issue by ChristianWunderlich** [gusye1234/nano-vectordb#6]
I´m troubleshooting a different project which utilizes your framework. I would like to see whats inide the vector stores, but I just see a handful of information before the remaining content is hashed. Is there a switch to turn off hashing? I know this got implemented for storage size reasons, but it would make troubleshooting so much more easy in case this can be turned off ;-) Thanks!

**Comment by gusye1234** [comment]
Are you trying to have a look at the embedding floats? Cause in `nano-vectordb`, the embedding matrix is the only one that hashed(encoded) into string.

**Comment by Kenwwww** [comment]
@gusye1234  Are there any way to decode back？Though it‘s seems impossible...😭

**Comment by gusye1234** [comment]
Of course, it just a base64-decoded string, nano-vectordb has a function to decode it back to `numpy.array`:

https://github.com/gusye1234/nano-vectordb/blob/a20e63e04df9d412c734f96b9026b74ffcfa5ee0/nano_vectordb/dbs.py#L31C1-L32

**Comment by Kenwwww** [comment]
> Of course, it just a base64-decoded string, nano-vectordb has a function to decode it back to `numpy.array`:
> 
> https://github.com/gusye1234/nano-vectordb/blob/a20e63e04df9d412c734f96b9026b74ffcfa5ee0/nano_vectordb/dbs.py#L31C1-L32

greate work！
